remove object file

diff --git a/chap3/makefile b/chap3/makefile
--- a/chap3/makefile
+++ b/chap3/makefile
@@ -7,8 +7,8 @@ parsetest.o: parsetest.c errormsg.h util.h
 y.tab.o: y.tab.c
 	cc -g -c y.tab.c
 
-y.tab.c: tiger.grm
-	yacc -dv tiger.grm
+y.tab.c: tiger.y
+	yacc -b y -d -v tiger.y
 
 y.tab.h: y.tab.c
 	echo "y.tab.h was created at the same time as y.tab.c"
@@ -27,3 +27,28 @@ util.o: util.c util.h
 
 clean: 
 	rm -f a.out util.o parsetest.o lex.yy.o errormsg.o y.tab.c y.tab.h y.tab.o
+
+test:
+	@for num in {1..49}; do \
+		fname="../testcases/test$$num.tig"; \
+		echo "syntax analyze $$fname ... \c"; \
+		./a.out $$fname > test.log 2>&1; \
+		if [[ $$(echo $$?) != 0 ]]; then \
+			echo "fail"; \
+			exit 1; \
+		else \
+			echo "success"; \
+		fi \
+	done
+	@for file in merge.tig queens.tig; do \
+		fname="../testcases/$$file"; \
+		echo "syntax analyze $$fname ... \c"; \
+		./a.out $$fname > test.log 2>&1; \
+		if [[ $$(echo $$?) != 0 ]]; then \
+			echo "fail"; \
+			break; \
+		else \
+			echo "success"; \
+		fi \
+	done
+
